require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'kids' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'


  pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  target 'kidsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'kids-tvOS' do
  # Pods for kids-tvOS

  target 'kids-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
